// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhTJ8NEpZmiVn1xkanIwiQqHYtrFUABL0',
    appId: '1:251166023993:web:75f000c1f73b9a5ae8c8e8',
    messagingSenderId: '251166023993',
    projectId: 'ruet-archieve-new',
    authDomain: 'ruet-archieve-new.firebaseapp.com',
    storageBucket: 'ruet-archieve-new.firebasestorage.app',
    measurementId: 'G-DLVV5B9B3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4w7Oj9fAUh5jGC5t_tx8vMM7I8J5Vsqc',
    appId: '1:251166023993:android:b42776f9329c8db0e8c8e8',
    messagingSenderId: '251166023993',
    projectId: 'ruet-archieve-new',
    storageBucket: 'ruet-archieve-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaP1tm7tl4a2aX3PLVFCPtYfP7R2P2pf4',
    appId: '1:251166023993:ios:98e2a792f20ab1f9e8c8e8',
    messagingSenderId: '251166023993',
    projectId: 'ruet-archieve-new',
    storageBucket: 'ruet-archieve-new.firebasestorage.app',
    androidClientId: '251166023993-628v9cvc7cm04b60furb2dhvhmvmceca.apps.googleusercontent.com',
    iosClientId: '251166023993-qutv962p1gjdb1hn1l48j101l02ceg2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruetArchiveNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaP1tm7tl4a2aX3PLVFCPtYfP7R2P2pf4',
    appId: '1:251166023993:ios:98e2a792f20ab1f9e8c8e8',
    messagingSenderId: '251166023993',
    projectId: 'ruet-archieve-new',
    storageBucket: 'ruet-archieve-new.firebasestorage.app',
    androidClientId: '251166023993-628v9cvc7cm04b60furb2dhvhmvmceca.apps.googleusercontent.com',
    iosClientId: '251166023993-qutv962p1gjdb1hn1l48j101l02ceg2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruetArchiveNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhTJ8NEpZmiVn1xkanIwiQqHYtrFUABL0',
    appId: '1:251166023993:web:7a9ce3616adc59c6e8c8e8',
    messagingSenderId: '251166023993',
    projectId: 'ruet-archieve-new',
    authDomain: 'ruet-archieve-new.firebaseapp.com',
    storageBucket: 'ruet-archieve-new.firebasestorage.app',
    measurementId: 'G-7773X7VS4B',
  );
}
